# version: "3.8"

# services:
#   app1:
#     build:
#       context: ./rust_nginx
#     environment:
#       - APP_NAME=App1
#     ports:
#       - "8081:8080"

#   app2:
#     build:
#       context: ./rust_nginx
#     environment:
#       - APP_NAME=App2
#     ports:
#       - "8082:8080"

#   app3:
#     build:
#       context: ./rust_nginx
#     environment:
#       - APP_NAME=App3
#     ports:
#       - "8083:8080"

#   nginx:
#     build:
#       context: ./nginx
#     ports:
#       - "8080:8080"
#     depends_on:
#       - app1
#       - app2
#       - app3

version: "3.8"

services:
  app1:
    build:
      context: ./rust_nginx
    environment:
      - APP_NAME=App1
    expose:
      - "8080"

  app2:
    build:
      context: ./rust_nginx
    environment:
      - APP_NAME=App2
    expose:
      - "8080"

  app3:
    build:
      context: ./rust_nginx
    environment:
      - APP_NAME=App3
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - app3
